#pragma once

#include <cstdint>

namespace besm::dec {

enum format_t { ILLEGAL, R, I, S, B, U, J };

constexpr static uint8_t OPCODE2FORMAT[128] = {
    ILLEGAL, ILLEGAL, ILLEGAL, I,       ILLEGAL, ILLEGAL, ILLEGAL, ILLEGAL,
    ILLEGAL, ILLEGAL, ILLEGAL, ILLEGAL, ILLEGAL, ILLEGAL, ILLEGAL, I,
    ILLEGAL, ILLEGAL, ILLEGAL, I,       ILLEGAL, ILLEGAL, ILLEGAL, U,
    ILLEGAL, ILLEGAL, ILLEGAL, I,       ILLEGAL, ILLEGAL, ILLEGAL, ILLEGAL,
    ILLEGAL, ILLEGAL, ILLEGAL, S,       ILLEGAL, ILLEGAL, ILLEGAL, ILLEGAL,
    ILLEGAL, ILLEGAL, ILLEGAL, ILLEGAL, ILLEGAL, ILLEGAL, ILLEGAL, ILLEGAL,
    ILLEGAL, ILLEGAL, ILLEGAL, R,       ILLEGAL, ILLEGAL, ILLEGAL, U,
    ILLEGAL, ILLEGAL, ILLEGAL, R,       ILLEGAL, ILLEGAL, ILLEGAL, ILLEGAL,
    ILLEGAL, ILLEGAL, ILLEGAL, ILLEGAL, ILLEGAL, ILLEGAL, ILLEGAL, ILLEGAL,
    ILLEGAL, ILLEGAL, ILLEGAL, ILLEGAL, ILLEGAL, ILLEGAL, ILLEGAL, ILLEGAL,
    ILLEGAL, ILLEGAL, ILLEGAL, ILLEGAL, ILLEGAL, ILLEGAL, ILLEGAL, ILLEGAL,
    ILLEGAL, ILLEGAL, ILLEGAL, ILLEGAL, ILLEGAL, ILLEGAL, ILLEGAL, ILLEGAL,
    ILLEGAL, ILLEGAL, ILLEGAL, B,       ILLEGAL, ILLEGAL, ILLEGAL, I,
    ILLEGAL, ILLEGAL, ILLEGAL, ILLEGAL, ILLEGAL, ILLEGAL, ILLEGAL, J,
    ILLEGAL, ILLEGAL, ILLEGAL, I,       ILLEGAL, ILLEGAL, ILLEGAL, ILLEGAL,
    ILLEGAL, ILLEGAL, ILLEGAL, ILLEGAL, ILLEGAL, ILLEGAL, ILLEGAL, ILLEGAL};

} // namespace besm::dec
