set(BESM666_GNU_TOOLCHAIN_BIN ${BESM666_RISCV_SYSROOT}/bin)

set(CMAKE_SYSTEM_NAME unknown)
set(CMAKE_SYSTEM_PROCESSOR riscv64)
set(CMAKE_SYSROOT ${BESM666_FAKEROOT})

set(CMAKE_C_COMPILER ${BESM666_GNU_TOOLCHAIN_BIN}/riscv64-unknown-elf-gcc)
set(CMAKE_CXX_COMPILER ${BESM666_GNU_TOOLCHAIN_BIN}/riscv64-unknown-elf-g++)
set(CMAKE_LINKER ${BESM666_GNU_TOOLCHAIN_BIN}/riscv64-unknown-elf-ld)
set(CMAKE_OBJCOPY ${BESM666_GNU_TOOLCHAIN_BIN}/riscv64-unknown-elf-objcopy)
set(CMAKE_STRIP ${BESM666_GNU_TOOLCHAIN_BIN}/riscv64-unknown-elf-strip)
set(CMAKE_CPP ${BESM666_GNU_TOOLCHAIN_BIN}/riscv64-unknown-elf-cpp)

set(CMAKE_FIND_ROOT_PATH ${BESM666_GNU_TOOLCHAIN_BIN})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)

