name: clang-format check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  formatting-check:
    name: Formatting Check of ${{ github.workspace }}/${{ matrix.path }} directory
    strategy:
      matrix:
        path:
          - 'src'
          - 'include'
          - 'unit_test'
          - 'standalone'
        os: [ ubuntu-latest, macos-12 ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Run clang-format style check for C/C++/Protobuf programs.
      uses: jidicula/clang-format-action@v4.9.0
      with:
        clang-format-version: '16'
        check-path: ${{ github.workspace }}/${{ matrix.path }}
