---
name: pdd
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
concurrency:
  group: pdd-${{ github.ref }}
  cancel-in-progress: true
jobs:
  pdd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: g4s8/pdd-action@master
